if(LPM_ENABLE_CLANG_TIDY)
  find_program(CLANG_TIDY_EXE NAMES clang-tidy-21 clang-tidy-20 clang-tidy-19 clang-tidy-18 clang-tidy)
  if(CLANG_TIDY_EXE)
    set(CMAKE_C_CLANG_TIDY "${CLANG_TIDY_EXE}")
    message(STATUS "[liblpm] clang-tidy enabled: ${CLANG_TIDY_EXE}")
  else()
    message(STATUS "[liblpm] clang-tidy not found -- skipping static analysis")
  endif()
endif()
